#!/usr/bin/env python3
"""Turn the eIM's byte-exact ASN.1 vectors (checked against pycrate there)
into a C header: tests/vectors.h. Source: <eim>/crates/eim-asn1/tests/.

    tests/gen_vectors.py ~/projects/eim > tests/vectors.h
"""
import glob, json, os, sys

root = os.path.join(sys.argv[1], 'crates/eim-asn1/tests')
print('/* generated by tests/gen_vectors.py from the eIM test vectors, do not edit */')
print('struct vec { const char *file, *type, *label, *hex; };')
print('static const struct vec VECTORS[] = {')
for f in sorted(glob.glob(os.path.join(root, 'vectors*.json'))):
    for v in json.load(open(f)):
        print('\t{ "%s", "%s", "%s", "%s" },' % (os.path.basename(f), v.get('type', ''),
              v.get('label', ''), v['hex']))
print('};')
